
setopt inc_append_history

# ALIASES
alias ls="ls --color=auto -hv"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# Safe version of rm and mv
alias rm='echo "rm is disabled, use remove or trash or /bin/rm instead."'
alias remove="/bin/rm -irv"
alias mv="mv -i"

# ZOXIDE??

# make homebrew apps available on path
eval "$(/opt/homebrew/bin/brew shellenv)"

# COMMAND PROMPT
eval "$(starship init zsh)"

# SYNTAX HIGHLIGHTING
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Da tenere sempre alla fine del file!
